### ISSUE TITLE
missing packages for el9 build

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-appliance#25]
Missing el9 builds for https://github.com/oVirt/buildcontainer/blob/main/Dockerfile.stream8#L49
@sandrobonazzola do they exist or need to be built by us?

**Comment by michalskrivanek** [comment]
needed for #24

**Comment by sandrobonazzola** [comment]
Aligned el8 and el9 tooling:
* [oz-0.18.0-2.el8](https://cbs.centos.org/koji/buildinfo?buildID=37613)
* [oz-0.18.0-2.el9](https://cbs.centos.org/koji/buildinfo?buildID=37612)

* [imagefactory-1.1.16-1.el8](https://cbs.centos.org/koji/buildinfo?buildID=37615)
* [imagefactory-1.1.16-1.el9](https://cbs.centos.org/koji/buildinfo?buildID=37614)

* [imagefactory-plugins-1.1.16-1.el8](https://cbs.centos.org/koji/buildinfo?buildID=37618)
* [imagefactory-plugins-1.1.16-1.el9](https://cbs.centos.org/koji/buildinfo?buildID=37617)

* [python-sh-1.12.14-15.el8](https://cbs.centos.org/koji/buildinfo?buildID=37260) - using older due to [amoffat/sh/issues/600](https://github.com/amoffat/sh/issues/600)
* [python-sh-1.14.2-5.el9](https://cbs.centos.org/koji/buildinfo?buildID=37616)

**Comment by michalskrivanek** [comment]
thank you, sandro!
